# Generated by Django 3.1.2 on 2021-01-12 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devs_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ureg',
            name='zip',
            field=models.IntegerField(),
        ),
    ]
